---
- name: Create a vault with a secret
  hosts: localhost
  connection: local

  tasks:
  - name: Create instance of Key Vault
    azure.azcollection.azure_rm_keyvault:
      resource_group: "{{ resource_group }}"
      vault_name: "vault{{ vaultname }}"
      enabled_for_deployment: yes
      vault_tenant: "{{ tenant_id }}"
      sku:
        name: standard
        family: A
      access_policies:
        - tenant_id: "{{ tenant_id }}"
          object_id: "{{ object_id }}"
          keys:
            - get
            - list
            - update
            - create
            - import
            - delete
            - recover
            - backup
            - restore
          secrets:
            - get
            - list
            - set
            - delete
            - recover
            - backup
            - restore
    register: output
  - name: create a kevyault secret
    azure.azcollection.azure_rm_keyvaultsecret:
      keyvault_uri: https://vault{{ vaultname }}.vault.azure.net
      secret_name: "{{ secret_name }}"
      secret_value: "{{ secret_value }}"
      content_type: 'Content Type Secret'
    register: output
  - name: Get secret current version
    azure.azcollection.azure_rm_keyvaultsecret_info:
      vault_uri: https://vault{{ vaultname }}.vault.azure.net
      name: "{{ secret_name }}"
    register: facts
