---
- name: Print secret from vault
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Get secret value from vault
    azure.azcollection.azure_rm_keyvaultsecret_info:
      vault_uri: "{{ vault_uri }}"
      name: "{{ secret_name }}"
    register: AzureSecret

  - name: Debug it
    debug:
      msg: "{{ AzureSecret }}"
